#github repository Actions 페이지에 나타낼 이름
name: CI/CD

# event trigger
on:
  push:
    branches:
        ["main"]
  pull_request:
      branches:
        ["main"]

permissions:
  contents: read

jobs:
  CI-CD:
    runs-on: ubuntu-22.04
    steps:

    ## jdk setting
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin' # https://github.com/actions/setup-java

    ## gradle caching
    - name: Gradle Caching
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
          

    # create application-prod.properties
    - name: make application-prod.properties
      if: contains(github.ref, 'main')
      run: |
          cd ./src/main
          mkdir resources
          cd ./resources

          touch ./application.properties
          echo "${{ secrets.PROPERTIES_PROD }}" >> ./application.properties
      shell: bash

#
### try~~~~
#      # create application-aws.properties
#    - name: Make application.properties
#      if: contains(github.ref, 'master')
#      run: |
#        cd ./src/main/resources
#        rm ./application.properties
#
#        ls -al
#        touch ./application.properties
#
#        echo "copy properties"
#        echo "${{ secrets.MYSQL_DATABASE_PROPERTIES }}" >> ./application.properties
#      shell: bash

      ## gradle build
    - name: Build with Gradle
      run: |
       chmod +x gradlew
       ./gradlew clean build -x test
       ls -l build/libs

    - name: Check build directory
      run: |
        ls -R build

    - name: CHECK THIS directory
      run: |
        pwd

    # ## copy jar file
    - name: Copy jar file
      run: cp build/libs/*-0.0.1-SNAPSHOT.jar app.jar
      
    - name: List directory
      run: ls -R
      
    ## docker build & push to production
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Docker login
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    - name: Docker build
      run: |
        docker build -t ${{ secrets.DOCKER_REPO }} -f Dockerfile .
    - name: List directory
      run: ls -R
    - name: Docker push
      run: |
        docker push ${{ secrets.DOCKER_REPO }}
    ## deploy to production
    - name: Deploy to prod
      uses: appleboy/ssh-action@master
      id: deploy-prod
      if: contains(github.ref, 'main')
      with:
          host: ${{ secrets.HOST_PROD }}
          username: ubuntu
          key: ${{ secrets.PRIVATE_KEY }}
          envs: GITHUB_SHA
          script: |
            sudo docker stop $(sudo docker ps -a -q)
            sudo docker rm $(sudo docker ps -a -q)
            sudo docker image rm ${{ secrets.DOCKER_REPO }}
            sudo docker pull ${{ secrets.DOCKER_REPO }}
            sudo docker run -d -p 8080:8080 ${{ secrets.DOCKER_REPO }}
  ## time
  current-time:
    needs: CI-CD
    runs-on: ubuntu-latest
    steps:
      - name: Get Current Time
        uses: 1466587594/get-current-time@v2
        id: current-time
        with:
          format: YYYY-MM-DDTHH:mm:ss
          utcOffset: "+09:00" # 기준이 UTC이기 때문에 한국시간인 KST를 맞추기 위해 +9시간 추가

      - name: Print Current Time
        run: echo "Current Time=${{steps.current-time.outputs.formattedTime}}" # current-time 에서 지정한 포맷대로 현재 시간 출력
        shell: bash
